//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CescoDeviceExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HostName=CescoIotHubTest.azure-devices.net;SharedAccessKeyName=iothubownerexplore" +
            "r;SharedAccessKey=yvywtPcJDn96CrrnEGXhn3j0ukWUFiC7tWArsq8ZfWQ=")]
        public string TEST {
            get {
                return ((string)(this["TEST"]));
            }
            set {
                this["TEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HostName=CESCOIotHubDev.azure-devices.net;SharedAccessKeyName=iothubownerexplorer" +
            ";SharedAccessKey=t1xqcLY4DD9IdqEEr00yByhAHagcM/TYc2A7qcj6FFE=")]
        public string DEV {
            get {
                return ((string)(this["DEV"]));
            }
            set {
                this["DEV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HostName=CescoIotHub.azure-devices.net;SharedAccessKeyName=iothubownerexplorer;Sh" +
            "aredAccessKey=BWbzZcvrs/b6zpPExrdElfg3x1Dbxwc78OYiwvQpElk=")]
        public string REAL {
            get {
                return ((string)(this["REAL"]));
            }
            set {
                this["REAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Azure\\DeviceList.json")]
        public string DeviceList {
            get {
                return ((string)(this["DeviceList"]));
            }
            set {
                this["DeviceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\AzureLog\\")]
        public string LoggingPath {
            get {
                return ((string)(this["LoggingPath"]));
            }
            set {
                this["LoggingPath"] = value;
            }
        }
    }
}
